# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: mta
steps:
- bash: 'mtaBuild --version'
