# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: cd-openui5-sample-app
resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: build  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Build MTA # friendly name to display in the UI
  jobs:
    job: build
    steps:
      - bash: 'mtaBuild --build-target NEO --mtar out.mtar build'

- stage: deploy
  displayName: Deploy to SAP Cloud Platform (neo)
	dependsOn: build
  jobs:
    job: build
    steps:
      - bash: 'mtaBuild --build-target NEO --mtar out.mtar build'

container: mta
