# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0
  - container: neo
    image: 'ppiper/neo-cli'
    options: --user 0:0


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: mta
steps:
- bash: 'mtaBuild --build-target NEO --mtar out.mtar build'

container neo
steps 
- bash: 'neo.sh help'
