# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: cd-openui5-sample-app
resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0
  - container: neo
    image: 'ppiper/neo-cli:latest'
    options: --user 0:0

trigger:
- master

stages:
- stage: build  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Build MTA # friendly name to display in the UI
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      container: mta
      steps:
        - bash: 'mtaBuild --build-target NEO --mtar out.mtar build'
        artifact: out.mtar

- stage: deploy
  displayName: Deploy to SAP Cloud Platform (neo)
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      #container: neo
      steps:
        - bash: 'docker build -t local/neo-cli https://github.com/SAP/devops-docker-images.git#pr/bash-for-neo:neo-cli'
        - bash: 'docker run local/neo-cli neo.sh deploy-mta --host ondemand.hana.com --account r15qd7iy5l --source out.mtar -u $(USER) -p $(PASSWORD)'


