# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: cd-openui5-sample-app
resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged
  - container: node
    image: 'geekykaran/headless-chrome-node-docker:latest'
    options: --privileged

trigger:
- master

stages:
- stage: build
  displayName: Build MTA for SAP Cloud Platform
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      container: mta
      steps:
        - bash: 'mtaBuild --build-target CF --mtar MySampleApp.mtar build'
        - publish: $(System.DefaultWorkingDirectory)/.
          artifact: WebApp

- stage: test
  displayName: Run Karma Test Suite
  jobs:
    - job: test
      pool:
        vmImage: 'ubuntu-latest'
      container: node
      steps:
        - bash: 'npm install && npm run-script test'

- stage: deploy
  displayName: Deployment to SAP Cloud Platform (neo)
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - download: current
          artifact: WebApp
        - bash: 'docker build -t local/neo-cli https://github.com/SAP/devops-docker-neo-cli'
        - bash: 'docker run -v $(Pipeline.Workspace)/WebApp/:/data -w /data local/neo-cli neo.sh deploy-mta --host "$(NEO_HOST)" --account "$(NEO_ACCOUNT)" --source "MySampleApp.mtar" -u "$(NEO_USER)" -p "$(NEO_PASSWORD)"'
