# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: cd-openui5-sample-app
resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0
  - container: neo
    image: 'ppiper/neo-cli:latest'
  - container: node
    image: 'geekykaran/headless-chrome-node-docker:latest'
    options: --privileged


trigger:
- master

stages:
- stage: build
  displayName: Build MTA for SAP Cloud Platform
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      container: mta
      steps:
        - bash: 'mtaBuild --build-target NEO --mtar $(Build.ArtifactStagingDirectory)/out.mtar build'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'mtar'
            publishLocation: 'Container'

- stage: test
  displayName: Run Karma Test Suite
  jobs:
    - job: test
      pool:
        vmImage: 'ubuntu-latest'
      container: node
      steps:
        - bash: 'npm install && npm run-script test'

- stage: deploy
  displayName: Deployment to SAP Cloud Platform (neo)
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      container: neo
      steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            artifactName: 'mtar'
            buildType: 'current'
            downloadType: 'single'
            downloadPath: '$(System.ArtifactsDirectory)'
     #   - bash: 'docker build -t local/neo-cli https://github.com/SAP/devops-docker-images.git#pr/bash-for-neo:neo-cli'
        - bash: 'neo.sh deploy-mta --host "$(NEO_HOST)" --account "$(NEO_ACCOUNT)" --source "out.mtar" -u "$(NEO_USER)" -p "$(NEO_PASSWORD)"'
