#Steps Specific Configuration
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry: 
      apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
      appName: 'cfAppName'
      credentialsId: 'cfCredentialsId'
      org: 'CI/CDInternalDemos_htmls5'
      space: 'html5apps'
    deployTool: 'cf_native'
