general:
  jenkinsKubernetes:
    jnlpAgent: 'docker.wdf.sap.corp:50001/sap-production/jnlp-alpine:3.26.1-sap-02'
#Steps Specific Configuration
steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
    deployMode: mta
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'r15qd7iy5l'
      host: 'hana.ondemand.com'
  
