#Steps Specific Configuration
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry: 
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      appName: 'csdemo'
      credentialsId: 'CF_CREDENTIALS_ID'
      org: 'piper'
      space: 'demo'
    deployTool: 'cf_native'
