#Steps Specific Configuration
steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
    deployMode: mta
    neo:
      neoCredentialsId: 'NEO_DEPLOY'
      account: 'r15qd7iy5l'
      host: 'hana.ondemand.com'
